//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOHFW_APPLICATION.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOH_MST_STATE
    {
        public decimal StateID_N { get; set; }
        public string StateCode_V { get; set; }
        public Nullable<decimal> StateTypeID_N { get; set; }
        public string StateName_V { get; set; }
        public Nullable<decimal> AreaCovered_N { get; set; }
        public Nullable<System.DateTime> ActiveFrom_D { get; set; }
        public Nullable<System.DateTime> ActiveTo_D { get; set; }
        public string ActiveFlag_C { get; set; }
        public System.DateTime CreatedOn_D { get; set; }
        public Nullable<System.DateTime> UpdatedOn_D { get; set; }
        public Nullable<decimal> DeletedBy_N { get; set; }
        public Nullable<System.DateTime> DeletedOn_D { get; set; }
        public Nullable<System.DateTime> StagedDate_D { get; set; }
        public string StagedFlag_C { get; set; }
        public decimal CreatedBy_N { get; set; }
        public Nullable<decimal> UpdatedBy_N { get; set; }
        public string StateCategory_V { get; set; }
        public string Remarks_V { get; set; }
        public Nullable<decimal> SeqNo_n { get; set; }
        public string IsFacilityDelete_C { get; set; }
        public string IsFacilityReset { get; set; }
        public Nullable<decimal> PREVIOUS_StateID_N { get; set; }
        public string SPLIT_FLAG_C { get; set; }
    }
}
