//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOHFW_APPLICATION.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOH_TRN_SERVICE_DATA
    {
        public decimal ServiceEntryID_N { get; set; }
        public string Code_V { get; set; }
        public Nullable<int> ServiceCategoryID_N { get; set; }
        public string Value_N { get; set; }
        public string Name_V { get; set; }
        public Nullable<int> ModuleID_N { get; set; }
        public string ModuleName_V { get; set; }
        public Nullable<int> Formid_n { get; set; }
        public string FormName_V { get; set; }
        public Nullable<int> FinyearID_N { get; set; }
        public string FinYearName_V { get; set; }
        public string Periodicity_C { get; set; }
        public Nullable<int> HMISIndicatorID_N { get; set; }
        public Nullable<int> DetailID_N { get; set; }
        public string DefaultValue_N { get; set; }
        public string Record_Type { get; set; }
        public Nullable<bool> Is_Value { get; set; }
        public Nullable<int> DistrictID_N { get; set; }
        public string DistrictName_V { get; set; }
        public Nullable<int> StateID_N { get; set; }
        public string StateName_V { get; set; }
        public string ClientHeaderValue_V { get; set; }
    }
}
