//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOHFW_APPLICATION.DATA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MOHFW_MIS_Entities : DbContext
    {
        public MOHFW_MIS_Entities()
            : base("name=MOHFW_MIS_Entities")
        {
            var ensureDLLIsCopied =
                System.Data.Entity.SqlServer.SqlProviderServices.Instance; 
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MOH_MST_STATE> MOH_MST_STATE { get; set; }
        public virtual DbSet<MOH_TRN_SERVICE_DATA> MOH_TRN_SERVICE_DATA { get; set; }
    }
}
